<?php declare(strict_types=1);

namespace EdgeTelemetrics\JSON_RPC\Tests;

use EdgeTelemetrics\JSON_RPC\Notification;
use EdgeTelemetrics\JSON_RPC\Request;
use EdgeTelemetrics\JSON_RPC\RpcMessageInterface;
use PHPUnit\Framework\TestCase;
use RuntimeException;
use TypeError;

class RequestTest extends TestCase
{
    public function testConstructorWithoutIdGeneratesAStringId(): void
    {
        $request = new Request('ping');

        $this->assertIsString($request->getId());
        $this->assertMatchesRegularExpression('/^[0-9a-f]{10}$/', $request->getId());
    }

    public function testAutoGeneratedIdsAreUnique(): void
    {
        $this->assertNotSame((new Request('ping'))->getId(), (new Request('ping'))->getId());
    }

    public function testExplicitNullIdIsPreserved(): void
    {
        $request = new Request('ping', [], null);

        $this->assertNull($request->getId());
        $this->assertSame(
            ['jsonrpc' => '2.0', 'method' => 'ping', 'id' => null],
            $request->jsonSerialize()
        );
    }

    public function testExplicitZeroIdIsPreserved(): void
    {
        $request = new Request('ping', [], 0);

        $this->assertSame(0, $request->getId());
    }

    public function testExplicitStringIdIsPreserved(): void
    {
        $request = new Request('ping', [], 'abc-123');

        $this->assertSame('abc-123', $request->getId());
    }

    public function testExplicitIntIdIsPreserved(): void
    {
        $request = new Request('ping', [], 42);

        $this->assertSame(42, $request->getId());
    }

    public function testExplicitFloatIdIsTruncatedToInt(): void
    {
        $request = new Request('ping', [], 2.9);

        $this->assertSame(2, $request->getId());
    }

    public function testSetIdAcceptsStringIntFloatAndNull(): void
    {
        $request = new Request('ping');

        $request->setId('id');
        $this->assertSame('id', $request->getId());

        $request->setId(7);
        $this->assertSame(7, $request->getId());

        $request->setId(7.8);
        $this->assertSame(7, $request->getId());

        $request->setId(null);
        $this->assertNull($request->getId());
    }

    public function testSetIdRejectsInfiniteFloat(): void
    {
        $request = new Request('ping');

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('Invalid Id format. Must be a string, number, or null');
        $request->setId(INF);
    }

    public function testSetIdRejectsNotANumberFloat(): void
    {
        $request = new Request('ping');

        $this->expectException(RuntimeException::class);
        $request->setId(NAN);
    }

    public function testSetIdRejectsOutOfRangeFloat(): void
    {
        $request = new Request('ping');

        $this->expectException(RuntimeException::class);
        $request->setId(PHP_INT_MAX * 10.0);
    }

    public function testSetIdRejectsBoolean(): void
    {
        $request = new Request('ping');

        $this->expectException(TypeError::class);
        $request->setId(true);
    }

    public function testJsonSerializeIncludesMethodParamsAndId(): void
    {
        $request = new Request('sum', [1, 2], 10);

        $this->assertSame(
            ['jsonrpc' => '2.0', 'method' => 'sum', 'params' => [1, 2], 'id' => 10],
            $request->jsonSerialize()
        );
    }

    public function testJsonEncodeRoundTripMatchesSerializedShape(): void
    {
        $request = new Request('sum', ['a' => 1], 99);
        $decoded = json_decode(json_encode($request), true);

        $this->assertSame($request->jsonSerialize(), $decoded);
    }

    public function testRequestExtendsNotificationAndImplementsInterface(): void
    {
        $request = new Request('ping');

        $this->assertInstanceOf(Notification::class, $request);
        $this->assertInstanceOf(RpcMessageInterface::class, $request);
    }
}
